### ISSUE TITLE
Write a project requirements

### ISSUE THREAD

**Issue by myusufuw** [myusufuw/boundless-books#1]
# The Boundless Books: your one-stop online store for all things books!

Link: 
- UI Design: [Figma](https://www.figma.com/design/ltfVj92yGg1SX09zZ2WQY4/Boundless-Books?node-id=0-1&t=CqVHK9ooblmj6MDz-1)
- Website: https://boundless-book.myusufuw.com

Inspirations: 
- https://www.gramedia.com/
- https://arena-book-shop.myshopify.com/

Features:
- Homepage: 
  - Design: [Gramedia Homepage](https://www.gramedia.com/)
  - Hero section
  - Products catalogue
- Detail product:
  - Design: [Gramedia Detail Product](https://www.gramedia.com/products/atomic-habits-perubahan-kecil-yang-memberikan-hasil-luar-biasa)
  - Image
  - Title
  - Author
  - Description
  - Add to cart button
- Shopping Cart Page:
  - Design: [Arena Book Cart Page](https://arena-book-shop.myshopify.com/cart)
  - Order list
    - Image, title, price, quantity, total.
    - Remove item.
  - Checkout button
  - Continue shopping button
- Checkout page::
  - Design: [Arena Book Checkout Page](https://arena-book-shop.myshopify.com/checkouts/cn/Z2NwLXVzLWVhc3QxOjAxSjAySDY5SEg1VE5KODRXUUNBM1NaREhT?preview_theme_id=50568167505)
  - Order summary
    - Order list
    - Total price
    - Place order button
- Author Page:
  - Design: [Gramedia Author Page](https://www.gramedia.com/author/author-james-clear)
  - Name
  - Profile picture
  - Description
  - List of the books
    -  Title
    -  Image

**Comment by mhaidarhanif** [comment]
1. Later, link to Figma. Or can be in the README.
2. Each inspirations, can be annotated in each particular features.
3. Author might need a dedicatecd page.
